from dotenv import dotenv_values

settings = dotenv_values('.env')

MONGO_HOST = settings['MONGO_HOST']
MONGO_PORT = settings['MONGO_PORT']
MONGO_INITDB_ROOT_USERNAME = settings['MONGO_INITDB_ROOT_USERNAME']
MONGO_INITDB_ROOT_PASSWORD = settings['MONGO_INITDB_ROOT_PASSWORD']
# MONGO_INITDB_DATABASE = settings['']
# DATABASE_USERNAME = chef
# DATABASE_PASSWORD=password

MONGO_DB_URL = f'mongodb://{MONGO_INITDB_ROOT_USERNAME}:{MONGO_INITDB_ROOT_PASSWORD}@{MONGO_HOST}:{MONGO_PORT}'

REDIS_HOST = settings['REDIS_HOST']
REDIS_PORT = settings['REDIS_PORT']


SECRET_KEY = settings['SECRET_KEY']
